name: Example

on: push

jobs:
  version:
    name: Determine next release version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Determine next release version
        uses: nordicsemiconductor/cloud-get-next-version-action@saga
        id: version
        with:
          branch: saga

      - run: |
          NEXT_VERSION=${{ steps.version.outputs.nextRelease }}
          echo ${NEXT_VERSION}
