name: Example

on: push

jobs:
  version:
    name: Determine next release version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Determine next release version
        uses: nordicsemiconductor/cloud-get-next-version-action@saga
        id: version
        with:
          branch: saga

      - run: |
          NEXT_VERSION=${{ steps.version.outputs.nextRelease }}
          echo ${NEXT_VERSION}
