name: Example

on: push

jobs:
  version:
    name: Determine next release version
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Determine next release version
        uses: bifravst/get-next-version-action@saga
        id: version
        with:
          branch: saga

      - run: |
          NEXT_VERSION=${{ steps.version.outputs.nextRelease }}
          echo ${NEXT_VERSION}
